### ISSUE TITLE
Problem uploading forecast

### ISSUE THREAD

**Issue by RobertWalraven** [epiforecasts/covid19-forecast-hub-europe#1007]
I am trying to upload this week's forecast and it keeps failing for some unclear reason after 4 attempts.  Can someone please take a look at the submission for 2021-10-04-RobertWalraven-ESG and see if they can tell me what the problem is?

**Comment by RobertWalraven** [comment]
Lastest error message:
ERRORS FOUND EXITING BUILD...
* ERROR IN  data-processed/2021-10-04-RobertWalraven-ESG.csv
File does not match forecast file naming convention: <date>-<team>-<model>.csv

The file naming convention looks perfectly fine to me and is the same that I've always used.

**Comment by Bisaloo** [comment]
Hi @RobertWalraven, you seem to have figured it out. The problem since the beginning was the file that was added in the wrong place with your first commit. Your following commit added the file in the right place but did not delete the misplaced one. Your last commit, which deletes this file, fixed your issue.

We agree with you that errors message are not super helpful (or even completely misunderstand the problem) at the moment and we are working on improving this. Hopefully, the next time someone encounters this problem, they will have a nice error message ("File XXX is not in the correct location. Please move/remove it.")

When you have problems with your submission, please feel free to tag me (@bisaloo) or Kath, who usually handles your weekly submission. We are logged on GitHub most of the time and it's always the same kind of problems that cause validation failure. So it's easy for us to tell you what's wrong, you don't have to lose time figuring it out :smiley:

**Comment by kathsherratt** [comment]
@RobertWalraven - thank you for opening an issue to flag this and sorry for the trouble. As @Bisaloo said, we understand the error messages are frustratingly unclear about this problem, and a fix is in the pipeline. In the meantime always happy to help, thank you very much @Bisaloo for following this up!
Kath
