### ISSUE TITLE
Github actions

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/covid19-forecast-hub-europe#8]
https://github.com/epiforecasts/covid19-forecast-hub-europe/actions
- [X] Visualization/Validation/Evaluation
	This: 
	  ~~1) creates visualisation for a Shiny app and RKI viz~~
      ~~2) creates a static plot (which we don't need)~~
      ~~3) gets commit dates (not sure why) and performs data validation (currently deactivated)~~
      4) evaluates forecasts (can be done once a week)
    To be reviewed / confirmed with people from the Germany/Poland forecast hub how much of this is really needed
- [X] ~~MZ
    This downloads subnational data for Poland - not needed~~
- [X] ~~PR checks
    This performs the validation checks on submissions - we need it~~
- [X] ~~epiforecasts
    This pulls (or will eventually pull) epiforecasts forecasts - not needed~~
- [X] ~~RKI-data
    This downloads subnational data for Poland - not needed~~
- [X] ~~UCLA
    This downloads UCLA forecasts - not needed~~
- [X] ~~LANL
    This downloads LANL forecasts - not needed~~
- [X] ~~Geneva
    This downloads Geneva forecasts - not needed~~
- [X] ~~ECDC-JHU-DIVI
    This downloads ECDC/JHU data - we will need some version of this~~

**Comment by jbracher** [comment]
If you want to use the RKI viz you do need the step called "creates visualisation for a Shiny app" above. The respective codes and output csvs are still in the folder of the Shiny app because this is what they were initially used for, but the viz set up by our colleagues at RKI uses the same csv files. 

Specifically you need to generate the following:

-  files in the format of [truth_to_plot_ecdc.csv ](https://github.com/KITmetricslab/covid19-forecast-hub-de/blob/master/app_forecasts_de/data/truth_to_plot_ecdc.csv) and [truth_to_plot_jhu](https://github.com/KITmetricslab/covid19-forecast-hub-de/blob/master/app_forecasts_de/data/truth_to_plot_jhu.csv) for truth data (or actually you'll need to get rid of one of them, but you need to discuss with Fabian from RKI how to do that exactly). In our repo does that. The file data_preparation.R is no longer relevant.
- files in the format of [forecasts_to_plot.csv](https://github.com/KITmetricslab/covid19-forecast-hub-de/blob/master/app_forecasts_de/data/forecasts_to_plot.csv) for forecasts. You can probably get rid of some columns `truth_data_source, shift_ECDC, shift_JHU, first_commit_date`, but this will of course require adaptations from Fabian's side, otherwise the app will break. These files are currently generated by [data_preparation.py](https://github.com/KITmetricslab/covid19-forecast-hub-de/blob/master/app_forecasts_de/code/data_preparation.py) and [add_last_observed.py](https://github.com/KITmetricslab/covid19-forecast-hub-de/blob/master/app_forecasts_de/code/add_last_observed.py). The former does most of the work, the latter just adds the last observed values for each forecast, which is needed for plotting (I can't remember why there are different files for that). Especially data_preparation.py can be simplified considerably as some parts (columns truth_data_source, shift_ECDC, shift_JHU don't need to be generated as you only have one truth data source).

Daniel Wolffram has written these Python scripts, he's also on the Slack channel in case you have questions.

**Comment by sbfnk** [comment]
Might also actually want the actions that pull data from elsewhere as discussed elsewhere (to populate the platform if/when not many models are available).

**Comment by jbracher** [comment]
Visualization/Validation/Evaluation is one large block because these things are just run jointly on a regular basis. Evaluation would only be necessary once per week. Commit dates are likely not needed anymore. For a while we thought we'd mark late or corrected forecasts in the app.
